title = "Archives – Critical Distance"
description = '"Where is all the good writing about games?"'
url = "https://critical-distance.com/archives/feed/"
feed_url = "https://critical-distance.com/archives/feed/"
author = "Archives – Critical Distance"
slug = "archives-critical-distance"
lastupdated = "2026-08-06T21:59:23.147296669Z"
etag = '"de8282492ef350751d5df126d282855f"'
