title = "Archives – Critical Distance"
description = '"Where is all the good writing about games?"'
url = "https://critical-distance.com/archives/feed/"
feed_url = "https://critical-distance.com/archives/feed/"
author = "Archives – Critical Distance"
slug = "archives-critical-distance"
lastupdated = "2026-09-27T09:50:56.557969123Z"
etag = '"b9aeb5adf209aea007370b6c72270e39"'
