title = "Archives – Critical Distance"
description = '"Where is all the good writing about games?"'
url = "https://critical-distance.com/archives/feed/"
feed_url = "https://critical-distance.com/archives/feed/"
author = "Archives – Critical Distance"
slug = "archives-critical-distance"
lastupdated = "2026-09-08T13:04:55.431741062Z"
etag = '"e571248de64c0e23798a72ccab11c10d"'
