title = "Bruno Croci"
description = "Bruno Croci"
url = "https://crocidb.com//index.xml"
feed_url = "https://crocidb.com/index.xml"
author = "Bruno Croci"
slug = "bruno-croci"
lastupdated = "2026-09-08T13:04:56.215751931Z"
etag = '"6a86ca72-617a2"'
last_modified = "Thu, 20 Aug 2026 09:35:46 GMT"
