title = "Bruno Croci"
description = "Bruno Croci"
url = "https://crocidb.com//index.xml"
feed_url = "https://crocidb.com/index.xml"
author = "Bruno Croci"
slug = "bruno-croci"
lastupdated = "2026-08-07T00:30:00.934523288Z"
etag = '"6a74577c-617a2"'
last_modified = "Thu, 06 Aug 2026 09:44:28 GMT"
