title = "Bruno Croci"
description = "Bruno Croci"
url = "https://crocidb.com//index.xml"
feed_url = "https://crocidb.com/index.xml"
author = "Bruno Croci"
slug = "bruno-croci"
lastupdated = "2026-02-11T20:17:03.542584682Z"
