title = "Fabien Sanglard"
description = "Chronicles of software wizardry"
url = "https://fabiensanglard.net/rss.xml"
feed_url = "https://fabiensanglard.net/rss.xml"
author = "Fabien Sanglard"
slug = "fabien-sanglard"
lastupdated = "2026-09-08T13:04:56.722466413Z"
last_modified = "Sat, 22 Aug 2026 00:01:24 GMT"
