title = "Fabien Sanglard"
description = "Chronicles of software wizardry"
url = "https://fabiensanglard.net/rss.xml"
feed_url = "https://fabiensanglard.net/rss.xml"
author = "Fabien Sanglard"
slug = "fabien-sanglard"
lastupdated = "2026-07-07T12:30:59.145328944Z"
