title = "Drew DeVault's blog"
description = "Drew DeVault's blog - Blog"
url = "https://drewdevault.com"
feed_url = "https://drewdevault.com/blog/index.xml"
author = "Drew DeVault's blog"
slug = "drew-devault-s-blog"
lastupdated = "2026-09-08T13:04:55.208721973Z"
last_modified = "Tue, 08 Sep 2026 08:47:37 GMT"
