title = "Drew DeVault's blog"
description = "Drew DeVault's blog - Blog"
url = "https://drewdevault.com"
feed_url = "https://drewdevault.com/blog/index.xml"
author = "Drew DeVault's blog"
slug = "drew-devault-s-blog"
lastupdated = "2026-08-07T00:30:00.032644512Z"
last_modified = "Tue, 28 Jul 2026 10:38:52 GMT"
