title = "Eli Bendersky's website"
description = "Eli Bendersky's website"
url = "https://eli.thegreenplace.net/"
feed_url = "https://eli.thegreenplace.net/feeds/all.atom.xml"
author = "Eli Bendersky"
slug = "eli-bendersky-s-website"
lastupdated = "2026-05-22T08:27:17.767586674Z"
