title = "Eli Bendersky's website"
description = "Eli Bendersky's website"
url = "https://eli.thegreenplace.net/"
feed_url = "https://eli.thegreenplace.net/feeds/all.atom.xml"
author = "Eli Bendersky"
slug = "eli-bendersky-s-website"
lastupdated = "2026-09-08T13:04:56.722265486Z"
etag = '"4ed6c-65a11b97b9a21-gzip"'
last_modified = "Fri, 28 Aug 2026 01:53:53 GMT"
