title = "null program"
description = "null program"
url = "https://nullprogram.com"
feed_url = "http://nullprogram.com/feed/"
author = "Christopher Wellons"
slug = "null-program"
lastupdated = "2026-08-07T00:30:01.108872154Z"
etag = 'W/"6a21fdeb-2bd4b"'
last_modified = "Thu, 04 Jun 2026 22:36:27 GMT"
