title = "buttonmashing"
description = "Mashing buttons since 1984"
url = "http://buttonmashing.com/feed/"
feed_url = "http://buttonmashing.com/feed/"
author = ""
slug = "buttonmashing"
lastupdated = "2026-09-08T13:05:00.579059161Z"
etag = '"20f02eeb3e27404f797f3cd6df64db2f"'
last_modified = "Wed, 22 Jul 2026 09:43:46 GMT"
