title = "buttonmashing"
description = "Mashing buttons since 1984"
url = "http://buttonmashing.com/feed/"
feed_url = "http://buttonmashing.com/feed/"
author = ""
slug = "buttonmashing"
lastupdated = "2026-09-21T09:42:43.551025384Z"
last_modified = "Wed, 9 Sep 2026 00:14:36 GMT"
