title = "Generalistic writings from @vlnn"
description = "Generalistic writings from @vlnn"
url = "https://vlnn.dev/"
feed_url = "https://vlnn.dev/rss.xml"
author = "Generalistic writings from @vlnn"
slug = "generalistic-writings-from-vlnn"
lastupdated = "2026-07-22T09:21:11.528930788Z"
