title = "Generalistic writings from @vlnn"
description = "Generalistic writings from @vlnn"
url = "https://vlnn.dev/"
feed_url = "https://vlnn.dev/rss.xml"
author = "Generalistic writings from @vlnn"
slug = "generalistic-writings-from-vlnn"
lastupdated = "2026-08-07T00:30:00.033915892Z"
etag = 'W/"6a7391a9-15f9b"'
last_modified = "Wed, 05 Aug 2026 19:40:25 GMT"
