title = "Ash's Blog"
description = "Recent content on Ash's Blog"
url = "https://ashvardanian.com/"
feed_url = "https://ashvardanian.com/index.xml"
author = "Ash's Blog"
slug = "ash-s-blog"
lastupdated = "2026-09-08T13:05:00.883219865Z"
etag = 'W/"6a9af49a-c461"'
last_modified = "Fri, 04 Sep 2026 16:40:58 GMT"
