title = "Ash's Blog"
description = "Recent content on Ash's Blog"
url = "https://ashvardanian.com/"
feed_url = "https://ashvardanian.com/index.xml"
author = "Ash's Blog"
slug = "ash-s-blog"
lastupdated = "2026-08-06T21:59:29.252869801Z"
etag = 'W/"69f71c8b-bf66"'
last_modified = "Sun, 03 May 2026 09:59:39 GMT"
