title = "Revista O Grito! — Jornalismo cultural que fala de tudo"
description = "Notícias, resenhas e artigos de arte, quadrinhos, cultura pop e cena independente"
url = "https://revistaogrito.com/feed/"
feed_url = "https://revistaogrito.com/feed/"
author = "Revista O Grito! — Jornalismo cultural que fala de tudo"
slug = "revista-o-grito-jornalismo-cultural-que-fala-de-tudo"
lastupdated = "2026-09-08T13:04:55.731089468Z"
etag = '"2c0c88c45c8741620822d9444da7248c"'
last_modified = "Tue, 08 Sep 2026 12:26:37 GMT"
