title = "Revista O Grito! — Jornalismo cultural que fala de tudo"
description = "Notícias, resenhas e artigos de arte, quadrinhos, cultura pop e cena independente"
url = "https://revistaogrito.com/feed/"
feed_url = "https://revistaogrito.com/feed/"
author = "Revista O Grito! — Jornalismo cultural que fala de tudo"
slug = "revista-o-grito-jornalismo-cultural-que-fala-de-tudo"
lastupdated = "2026-02-11T20:16:24.129735166Z"
