title = "Revista O Grito! — Jornalismo cultural que fala de tudo"
description = "Notícias, resenhas e artigos de arte, quadrinhos, cultura pop e cena independente"
url = "https://revistaogrito.com/feed/"
feed_url = "https://revistaogrito.com/feed/"
author = "Revista O Grito! — Jornalismo cultural que fala de tudo"
slug = "revista-o-grito-jornalismo-cultural-que-fala-de-tudo"
lastupdated = "2026-08-06T21:59:23.858713882Z"
etag = '"e9552e68b6599625476595ca223fc670"'
last_modified = "Tue, 04 Aug 2026 09:46:20 GMT"
