title = "absorptions"
description = "a blog about sound &amp; signals by windytan [oona räisänen]"
url = "https://www.windytan.com/feeds/posts/default"
feed_url = "https://www.windytan.com/feeds/posts/default"
author = "Oona Räisänen"
slug = "absorptions"
lastupdated = "2026-08-07T00:30:02.058710983Z"
etag = 'W/"d3bf3b1ff09d359f25bf6c9562f854f7b9a28238dbf00234df347ce50578c82a"'
last_modified = "Wed, 05 Aug 2026 15:09:00 GMT"
