title = "Nautilus"
description = "Science Connected"
url = "https://nautil.us/feed/"
feed_url = "https://nautil.us/feed/?_sp=4e7c3ce8-67d3-4a36-a885-f3c498dde540.1760345784905"
author = "Nautilus"
slug = "nautilus"
lastupdated = "2025-11-07T14:09:27.885954377Z"
