title = "The Codist"
description = "Four Decades Of Learning, Experiences, And Adventures"
url = "https://thecodist.com/"
feed_url = "http://feeds.feedburner.com/thecodist"
author = "The Codist"
slug = "the-codist"
lastupdated = "2026-08-07T00:30:04.088615486Z"
etag = 'W/"1f008-vtljnCrYTjYiNKSMaZXoYjIlkSw"'
