title = "Reasonably Polymorphic"
description = "Reasonably Polymorphic"
url = "https://reasonablypolymorphic.com"
feed_url = "https://reasonablypolymorphic.com/atom.xml"
author = "Sandy Maguire"
slug = "reasonably-polymorphic"
lastupdated = "2026-08-07T00:30:01.130587559Z"
etag = 'W/"6958468e-4f2b6"'
last_modified = "Fri, 02 Jan 2026 22:28:30 GMT"
