title = "Reasonably Polymorphic"
description = "Reasonably Polymorphic"
url = "https://reasonablypolymorphic.com"
feed_url = "https://reasonablypolymorphic.com/atom.xml"
author = "Sandy Maguire"
slug = "reasonably-polymorphic"
lastupdated = "2026-09-08T13:04:58.862363032Z"
etag = 'W/"6a8d360b-60fd4"'
last_modified = "Tue, 25 Aug 2026 06:28:27 GMT"
