title = "Archives – Critical Distance"
description = '"Where is all the good writing about games?"'
url = "https://critical-distance.com/archives/feed/"
feed_url = "https://critical-distance.com/archives/feed/"
author = "Archives – Critical Distance"
slug = "archives-critical-distance"
lastupdated = "2026-09-03T22:47:03.153585184Z"
etag = '"d6539f9d50139b466405425799f95c7f"'
