title = "lcamtuf’s thing"
description = "geek culture, algorithms, electronic circuit design, and chainsaw safety tips"
url = "https://lcamtuf.substack.com"
feed_url = "https://lcamtuf.substack.com/feed"
author = "lcamtuf"
slug = "lcamtuf-s-thing"
lastupdated = "2025-12-17T22:54:12.771897239Z"
