title = "LWN.net"
description = """
 LWN.net is a comprehensive source of news and opinions from
        and about the Linux community.  This is the main LWN.net feed,
        listing all articles which are posted to the site front page.
"""
url = "https://lwn.net"
feed_url = "https://lwn.net/headlines/rss"
author = "LWN.net"
slug = "lwn-net"
lastupdated = "2026-09-03T22:47:40.641424607Z"
etag = '"2d065862ad328bc7cf93bc33d45ce9aa9c0b72842c11a7ecb3fbaaefea76ab07"'
