title = "𝚟𝚎𝚛𝚖𝚊𝚍𝚎𝚗"
description = "Another ${RANDOM} sysadmin sharing his experiences of work at IT industry."
url = "https://vermaden.wordpress.com/feed/"
feed_url = "https://vermaden.wordpress.com/feed/"
author = "𝚟𝚎𝚛𝚖𝚊𝚍𝚎𝚗"
slug = "vermaden"
lastupdated = "2026-09-03T22:47:03.131131575Z"
last_modified = "Wed, 02 Sep 2026 20:42:35 GMT"
