title = "AksDev"
description = "Akseli's various rambles and posts about gaming, gamedev, FOSS, programming and other things."
url = "https://akselmo.dev"
feed_url = "https://akselmo.dev/feed.xml"
author = "Akseli"
slug = "aksdev"
lastupdated = "2026-08-07T00:30:00.408415034Z"
etag = '"1203b5-6578586923a82-gzip"'
last_modified = "Sun, 26 Jul 2026 15:47:40 GMT"
