title = "AksDev"
description = "Akseli's various rambles and posts about gaming, gamedev, FOSS, programming and other things."
url = "https://akselmo.dev"
feed_url = "https://akselmo.dev/feed.xml"
author = "Akseli"
slug = "aksdev"
lastupdated = "2026-05-27T23:22:57.207375024Z"
