title = "Tao of Mac"
description = "The Tao of Mac is the personal wiki of Rui Carmo, featuring a technology-oriented blog, links to articles, several compilations of resources around various key technology topics, and a collection of photos and videos."
url = "https://taoofmac.com"
feed_url = "https://taoofmac.com/atom.xml"
author = "Rui Carmo"
slug = "tao-of-mac"
lastupdated = "2026-04-15T10:42:49.428003473Z"
