title = "Scattered Thoughts"
description = "Scattered Thoughts"
url = "https://www.scattered-thoughts.net/atom.xml"
feed_url = "https://www.scattered-thoughts.net/atom.xml"
author = "Jamie Brandon"
slug = "scattered-thoughts"
lastupdated = "2026-09-03T22:47:03.658925573Z"
etag = '"6a8711b5-12963"'
last_modified = "Thu, 20 Aug 2026 14:39:49 GMT"
