title = "The Codist"
description = "Four Decades Of Learning, Experiences, And Adventures"
url = "https://thecodist.com/"
feed_url = "http://feeds.feedburner.com/thecodist"
author = "The Codist"
slug = "the-codist"
lastupdated = "2025-11-07T14:09:11.595818272Z"
