title = "The Codist"
description = "Four Decades Of Learning, Experiences, And Adventures"
url = "https://thecodist.com/"
feed_url = "http://feeds.feedburner.com/thecodist"
author = "The Codist"
slug = "the-codist"
lastupdated = "2025-10-31T14:47:18.149156982Z"
