title = "Reasonably Polymorphic"
description = "Reasonably Polymorphic"
url = "https://reasonablypolymorphic.com"
feed_url = "https://reasonablypolymorphic.com/atom.xml"
author = "Sandy Maguire"
slug = "reasonably-polymorphic"
lastupdated = "2025-12-19T13:26:58.509728630Z"
