title = "Reasonably Polymorphic"
description = "Reasonably Polymorphic"
url = "https://reasonablypolymorphic.com"
feed_url = "https://reasonablypolymorphic.com/atom.xml"
author = "Sandy Maguire"
slug = "reasonably-polymorphic"
lastupdated = "2025-10-31T14:47:20.515935203Z"
