title = "Reasonably Polymorphic"
description = "Reasonably Polymorphic"
url = "https://reasonablypolymorphic.com"
feed_url = "https://reasonablypolymorphic.com/atom.xml"
author = "Sandy Maguire"
slug = "reasonably-polymorphic"
lastupdated = "2025-12-17T22:54:16.875645701Z"
