title = "beware, the german!"
description = "beware, the german!"
url = "https://igerman.cc"
feed_url = "https://igerman.cc/rss.xml"
author = "german s."
slug = "beware-the-german"
lastupdated = "2026-08-06T22:26:01.197639512Z"
etag = '"djowzvfzyi9q3o0r"'
last_modified = "Fri, 03 Jul 2026 11:54:45 GMT"
