title = "beware, the german!"
description = "beware, the german!"
url = "https://igerman.cc"
feed_url = "https://igerman.cc/rss.xml"
author = "german s."
slug = "beware-the-german"
lastupdated = "2026-06-08T12:43:31.139582569Z"
