title = "andreinc"
description = "Personal blog of Andrei N. Ciobanu."
url = "/feed.xml"
feed_url = "https://www.andreinc.net/feed.xml"
author = "Andrei Ciobanu"
slug = "andreinc"
lastupdated = "2026-09-03T22:47:04.273133380Z"
etag = '"6c7bcecde7300b8c1fb6e48a643591b9"'
