title = "PotHix"
description = "Recent content on PotHix"
url = "https://pothix.com/"
feed_url = "http://feeds.feedburner.com/Pothix"
author = ""
slug = "pothix"
lastupdated = "2026-09-03T22:47:41.438985700Z"
last_modified = "Sat, 11 Jul 2026 11:48:02 GMT"
