title = "taylor.town"
description = "🐀🐀🐀🐀🐀🐀🐀🐀🐀"
url = "https://taylor.town"
feed_url = "https://taylor.town/feed.xml"
author = "Taylor Troesh"
slug = "taylor-town"
lastupdated = "2026-08-07T00:30:00.541638294Z"
etag = '"ad5035261c85a7c14f8706823937740f"'
