title = "Languages and Architecture"
description = "A blog on programming languages, software architecture, and Evan Ovadia's other shenanigans!"
url = "https://verdagon.dev/"
feed_url = "https://verdagon.dev/rss.xml"
author = "noreply@verdagon.dev (Evan Ovadia)"
slug = "languages-and-architecture"
lastupdated = "2026-02-11T20:17:03.815486343Z"
