title = "Languages and Architecture"
description = "A blog on programming languages, software architecture, and Evan Ovadia's other shenanigans!"
url = "https://verdagon.dev/"
feed_url = "https://verdagon.dev/rss.xml"
author = "noreply@verdagon.dev (Evan Ovadia)"
slug = "languages-and-architecture"
lastupdated = "2025-12-17T22:54:15.082897363Z"
