title = "buttonmashing"
description = "Mashing buttons since 1984"
url = "http://buttonmashing.com/feed/"
feed_url = "http://buttonmashing.com/feed/"
author = ""
slug = "buttonmashing"
lastupdated = "2026-09-03T22:47:03.753651511Z"
etag = '"52b5d3713487bebbf127cf03a09cd840"'
last_modified = "Thu, 19 Dec 2024 14:39:02 GMT"
