title = "Zig Devlog"
description = "Devlog"
url = "https://ziglang.org/devlog/"
feed_url = "https://ziglang.org/devlog/index.xml"
author = ""
slug = "zig-devlog"
lastupdated = "2026-08-07T00:30:01.937758538Z"
etag = 'W/"6a752566-2083d"'
last_modified = "Fri, 07 Aug 2026 00:23:02 GMT"
