title = "Zig Devlog"
description = "Devlog"
url = "https://ziglang.org/devlog/"
feed_url = "https://ziglang.org/devlog/index.xml"
author = ""
slug = "zig-devlog"
lastupdated = "2026-09-21T09:42:46.835119313Z"
etag = 'W/"6ab054c0-2678e"'
last_modified = "Sun, 20 Sep 2026 21:48:48 GMT"
