title = "Zig Devlog"
description = "Devlog"
url = "https://ziglang.org/devlog/"
feed_url = "https://ziglang.org/devlog/index.xml"
author = ""
slug = "zig-devlog"
lastupdated = "2026-02-11T20:17:06.535172968Z"
