title = "Tom Renner on My place to put things"
description = "Recent content in Tom Renner on My place to put things"
url = "https://tomrenner.com/"
feed_url = "https://tomrenner.com/index.xml"
author = "Tom Renner on My place to put things"
slug = "tom-renner-on-my-place-to-put-things"
lastupdated = "2025-11-07T14:09:09.117136347Z"
