title = "samwho.dev"
description = "Personal website of Sam Rose."
url = "https://samwho.dev/rss.xml"
feed_url = "https://samwho.dev/rss.xml"
author = "Unknown"
slug = "samwho-dev"
lastupdated = "2026-07-28T20:39:56.253178521Z"
