title = "samwho.dev"
description = "Personal website of Sam Rose."
url = "https://samwho.dev/rss.xml"
feed_url = "https://samwho.dev/rss.xml"
author = "Unknown"
slug = "samwho-dev"
lastupdated = "2026-08-24T15:49:17.796281802Z"
etag = 'W/"6a8778c9-d00"'
last_modified = "Thu, 20 Aug 2026 21:59:37 GMT"
