title = "samwho.dev"
description = "Personal website of Sam Rose."
url = "https://samwho.dev/rss.xml"
feed_url = "https://samwho.dev/rss.xml"
author = "Unknown"
slug = "samwho-dev"
lastupdated = "2026-02-11T20:17:05.958904518Z"
