title = "The Luddite"
description = "An Anticapitalist Tech Blog"
url = "https://theluddite.org"
feed_url = "http://theluddite.org/feed.rss"
author = ""
slug = "the-luddite"
lastupdated = "2026-08-07T00:30:01.142447588Z"
etag = '"6a6211f2-e93e7"'
last_modified = "Thu, 23 Jul 2026 13:06:58 GMT"
