title = "Eli Bendersky's website"
description = "Eli Bendersky's website"
url = "https://eli.thegreenplace.net/"
feed_url = "https://eli.thegreenplace.net/feeds/all.atom.xml"
author = "Eli Bendersky"
slug = "eli-bendersky-s-website"
lastupdated = "2025-12-19T13:26:52.586860821Z"
