title = "Michael W Lucas"
description = "Because no self-respecting AI would write this crap"
url = "https://mwl.io/feed"
feed_url = "https://mwl.io/feed"
author = "Michael W Lucas"
slug = "michael-w-lucas"
lastupdated = "2026-09-03T22:47:04.120444300Z"
etag = '"f155a5c01ea184653d098aa23f691dae"'
