title = "Michael W Lucas"
description = "Because no self-respecting AI would write this crap"
url = "https://mwl.io/feed"
feed_url = "https://mwl.io/feed"
author = "Michael W Lucas"
slug = "michael-w-lucas"
lastupdated = "2026-10-01T11:34:02.796064028Z"
etag = '"0ab9358996313ffc2757dee42a5d0584"'
last_modified = "Thu, 01 Oct 2026 09:14:32 GMT"
