title = "Michael W Lucas"
description = "Because no self-respecting AI would write this crap"
url = "https://mwl.io/feed"
feed_url = "https://mwl.io/feed"
author = "Michael W Lucas"
slug = "michael-w-lucas"
lastupdated = "2026-08-06T21:59:24.749805668Z"
etag = '"93c4c4b4eff7a47f3bfb958294c7b651"'
