title = "lcamtuf’s thing"
description = "geek culture, algorithms, electronic circuit design, and chainsaw safety tips"
url = "https://lcamtuf.substack.com"
feed_url = "https://lcamtuf.substack.com/feed"
author = "lcamtuf"
slug = "lcamtuf-s-thing"
lastupdated = "2026-08-06T21:59:23.858483209Z"
etag = 'W/"9f639-W7eWbSkkVPNlzPR9Z6N45lavSKo"'
