title = "Richard Stallman's Political Notes"
description = "Daily political notes about what is happening in the world."
url = "https://stallman.org/archives/polnotes.html"
feed_url = "https://stallman.org/rss/rss.xml"
author = "Richard Stallman's Political Notes"
slug = "richard-stallman-s-political-notes"
lastupdated = "2026-08-06T21:59:23.782351675Z"
etag = '"af4e-658546b2202f4-gzip"'
last_modified = "Wed, 05 Aug 2026 22:37:38 GMT"
