title = "Richard Stallman's Political Notes"
description = "Daily political notes about what is happening in the world."
url = "https://stallman.org/archives/polnotes.html"
feed_url = "https://stallman.org/rss/rss.xml"
author = "Richard Stallman's Political Notes"
slug = "richard-stallman-s-political-notes"
lastupdated = "2026-06-29T12:19:01.607235503Z"
