title = "gamedeveloper"
description = "Public RSS feed"
url = "https://www.gamedeveloper.com"
feed_url = "https://www.gamedeveloper.com/rss.xml"
author = "gamedeveloper"
slug = "gamedeveloper"
lastupdated = "2025-12-17T22:54:07.209014125Z"
