title = "gamedeveloper"
description = "Public RSS feed"
url = "https://www.gamedeveloper.com"
feed_url = "https://www.gamedeveloper.com/rss.xml"
author = "gamedeveloper"
slug = "gamedeveloper"
lastupdated = "2025-10-31T14:47:14.682078532Z"
