title = "Bruno Croci"
description = "Bruno Croci"
url = "https://crocidb.com//index.xml"
feed_url = "https://crocidb.com/index.xml"
author = "Bruno Croci"
slug = "bruno-croci"
lastupdated = "2025-10-31T14:47:22.509172393Z"
