title = "Bruno Croci"
description = "Bruno Croci"
url = "https://crocidb.com//index.xml"
feed_url = "https://crocidb.com/index.xml"
author = "Bruno Croci"
slug = "bruno-croci"
lastupdated = "2025-12-19T13:26:51.286680344Z"
