title = "Pluralistic: Daily links from Cory Doctorow"
description = "No trackers, no ads. Black type, white background. Privacy policy: we don't collect or retain any data at all ever period."
url = "https://pluralistic.net/feed/"
feed_url = "https://pluralistic.net/feed/"
author = "Pluralistic: Daily links from Cory Doctorow"
slug = "pluralistic-daily-links-from-cory-doctorow"
lastupdated = "2026-09-08T13:05:03.132704266Z"
etag = '"0d80d64deafd32e1b4e2091f5aa15ed1-gzip"'
last_modified = "Mon, 07 Sep 2026 06:14:24 GMT"
