title = "Pluralistic: Daily links from Cory Doctorow"
description = "No trackers, no ads. Black type, white background. Privacy policy: we don't collect or retain any data at all ever period."
url = "https://pluralistic.net/feed/"
feed_url = "https://pluralistic.net/feed/"
author = "Pluralistic: Daily links from Cory Doctorow"
slug = "pluralistic-daily-links-from-cory-doctorow"
lastupdated = "2026-08-07T00:30:02.019050092Z"
etag = '"30539e3058e80d01cfa5d2903b99be64-gzip"'
last_modified = "Thu, 06 Aug 2026 10:07:06 GMT"
