title = "Phoronix"
description = "Linux Hardware Reviews, Performance Benchmarks & Open-Source / Free Software News"
url = "https://www.phoronix.com/"
feed_url = "https://www.phoronix.com/rss.php"
author = "Phoronix"
slug = "phoronix"
lastupdated = "2026-07-06T19:13:02.737893222Z"
