title = "Phoronix"
description = "Linux Hardware Reviews, Performance Benchmarks & Open-Source / Free Software News"
url = "https://www.phoronix.com/"
feed_url = "https://www.phoronix.com/rss.php"
author = "Phoronix"
slug = "phoronix"
lastupdated = "2026-08-07T00:30:00.660644979Z"
last_modified = "Fri, 07 Aug 2026 00:26:48 GMT"
