title = "Phoronix"
description = "Linux Hardware Reviews, Performance Benchmarks & Open-Source / Free Software News"
url = "https://www.phoronix.com/"
feed_url = "https://www.phoronix.com/rss.php"
author = "Phoronix"
slug = "phoronix"
lastupdated = "2026-09-08T13:04:55.864644993Z"
last_modified = "Tue, 08 Sep 2026 13:01:28 GMT"
