title = "The Codist"
description = "Four Decades Of Learning, Experiences, And Adventures"
url = "https://thecodist.com/"
feed_url = "http://feeds.feedburner.com/thecodist"
author = "The Codist"
slug = "the-codist"
lastupdated = "2026-08-06T21:59:30.693305238Z"
etag = 'W/"1f008-89M/x1c5KL/PgKmaXhUL4OkaR5E"'
