title = "The Codist"
description = "Four Decades Of Learning, Experiences, And Adventures"
url = "https://thecodist.com/"
feed_url = "http://feeds.feedburner.com/thecodist"
author = "The Codist"
slug = "the-codist"
lastupdated = "2026-08-10T12:13:34.773390643Z"
