title = "Jonas Hietala"
description = "Jonas Hietala"
url = "https://www.jonashietala.se/feed.xml"
feed_url = "https://www.jonashietala.se/feed.xml"
author = "Jonas Hietala"
slug = "jonas-hietala"
lastupdated = "2025-10-31T14:47:16.063798276Z"
