title = "Jonas Hietala"
description = "Jonas Hietala"
url = "https://www.jonashietala.se/feed.xml"
feed_url = "https://www.jonashietala.se/feed.xml"
author = "Jonas Hietala"
slug = "jonas-hietala"
lastupdated = "2025-11-07T14:09:12.648802375Z"
