title = "Jonas Hietala"
description = "Jonas Hietala"
url = "https://www.jonashietala.se/feed.xml"
feed_url = "https://www.jonashietala.se/feed.xml"
author = "Jonas Hietala"
slug = "jonas-hietala"
lastupdated = "2026-02-11T20:16:55.704968008Z"
