title = "The Luddite"
description = "An Anticapitalist Tech Blog"
url = "https://theluddite.org"
feed_url = "http://theluddite.org/feed.rss"
author = ""
slug = "the-luddite"
lastupdated = "2025-12-19T13:26:43.538103379Z"
