title = "The Luddite"
description = "An Anticapitalist Tech Blog"
url = "https://theluddite.org"
feed_url = "http://theluddite.org/feed.rss"
author = ""
slug = "the-luddite"
lastupdated = "2025-10-31T14:47:09.702779339Z"
