title = "joshua stein"
description = "joshua stein"
url = "https://jcs.org/rss"
feed_url = "https://jcs.org/rss"
author = "joshua stein"
slug = "joshua-stein"
lastupdated = "2026-07-28T12:43:13.658080552Z"
