title = "joshua stein"
description = "joshua stein"
url = "https://jcs.org/rss"
feed_url = "https://jcs.org/rss"
author = "joshua stein"
slug = "joshua-stein"
lastupdated = "2026-09-28T20:25:30.367545630Z"
etag = '"6ab5df9a-331dc"'
