title = "joshua stein"
description = "joshua stein"
url = "https://jcs.org/rss"
feed_url = "https://jcs.org/rss"
author = "joshua stein"
slug = "joshua-stein"
lastupdated = "2026-08-06T22:26:01.836477816Z"
etag = '"6a67d5c3-331dc"'
