title = "Quanta Magazine"
description = "Illuminating science"
url = "https://www.quantamagazine.org/feed/"
feed_url = "https://www.quantamagazine.org/feed/"
author = "Quanta Magazine"
slug = "quanta-magazine"
lastupdated = "2025-11-07T14:09:28.431893833Z"
