title = "Entropic Thoughts"
description = ""
url = "https://entropicthoughts.com/feed.xml"
feed_url = "https://entropicthoughts.com/feed"
author = "a@xkqr.org (kqr)"
slug = "entropic-thoughts"
lastupdated = "2026-04-22T14:42:42.429665274Z"
