title = "Entropic Thoughts"
description = ""
url = "https://entropicthoughts.com/feed.xml"
feed_url = "https://entropicthoughts.com/feed"
author = "a@xkqr.org (kqr)"
slug = "entropic-thoughts"
lastupdated = "2026-09-23T18:24:54.420830766Z"
etag = 'W/"6ab27167-93c9"'
last_modified = "Tue, 22 Sep 2026 12:15:35 GMT"
