title = "Entropic Thoughts"
description = ""
url = "https://entropicthoughts.com/feed.xml"
feed_url = "https://entropicthoughts.com/feed"
author = "a@xkqr.org (kqr)"
slug = "entropic-thoughts"
lastupdated = "2026-08-07T00:30:00.033345363Z"
etag = '"6a72c704-8855"'
last_modified = "Wed, 05 Aug 2026 05:15:48 GMT"
