title = "Fabien Sanglard"
description = "Chronicles of software wizardry"
url = "https://fabiensanglard.net/rss.xml"
feed_url = "https://fabiensanglard.net/rss.xml"
author = "Fabien Sanglard"
slug = "fabien-sanglard"
lastupdated = "2026-08-07T00:30:02.080325348Z"
last_modified = "Tue, 14 Jul 2026 07:05:01 GMT"
