title = "Archives – Critical Distance"
description = '"Where is all the good writing about games?"'
url = "https://critical-distance.com/archives/feed/"
feed_url = "https://critical-distance.com/archives/feed/"
author = "Archives – Critical Distance"
slug = "archives-critical-distance"
lastupdated = "2025-10-31T14:47:14.202010312Z"
