title = "Jo's Blog"
description = "Jo's Blog"
url = "https://dead.garden/blog/index.html"
feed_url = "https://dead.garden/blog/feed.xml"
author = "Jo's Blog"
slug = "jo-s-blog"
lastupdated = "2026-06-07T00:26:10.609657011Z"
