title = "Jo's Blog"
description = "Jo's Blog"
url = "https://dead.garden/blog/index.html"
feed_url = "https://dead.garden/blog/feed.xml"
author = "Jo's Blog"
slug = "jo-s-blog"
lastupdated = "2026-08-07T00:29:59.920800301Z"
etag = '"6a725c0d-2dcc"'
last_modified = "Tue, 04 Aug 2026 21:39:25 GMT"
