title = "gamedeveloper"
description = "Public RSS feed"
url = "https://www.gamedeveloper.com"
feed_url = "https://www.gamedeveloper.com/rss.xml"
author = "gamedeveloper"
slug = "gamedeveloper"
lastupdated = "2026-08-07T00:30:00.802363664Z"
last_modified = "Fri, 07 Aug 2026 00:30:00 GMT"
