title = "gamedeveloper"
description = "Public RSS feed"
url = "https://www.gamedeveloper.com"
feed_url = "https://www.gamedeveloper.com/rss.xml"
author = "gamedeveloper"
slug = "gamedeveloper"
lastupdated = "2026-09-30T20:51:44.295133302Z"
last_modified = "Wed, 30 Sep 2026 20:51:43 GMT"
