title = "Lambda Land"
description = "Lambda: The Ultimate Blog Post—a blog mostly about programming languages, academia, and Emacs"
url = "https://lambdaland.org/atom.xml"
feed_url = "https://lambdaland.org/atom.xml"
author = """

            
              Ashton Wiersdorf
            
          """
slug = "lambda-land"
lastupdated = "2026-10-06T13:46:50.749334179Z"
etag = '"dlttrt6cwhyom98x"'
last_modified = "Thu, 01 Oct 2026 21:38:27 GMT"
