title = "Lambda Land"
description = "Lambda: The Ultimate Blog Post—a blog mostly about programming languages, academia, and Emacs"
url = "https://lambdaland.org/atom.xml"
feed_url = "https://lambdaland.org/atom.xml"
author = """

            
              Ashton Wiersdorf
            
          """
slug = "lambda-land"
lastupdated = "2026-09-08T13:04:56.354610152Z"
etag = '"dl9dc6l531erm5ux"'
last_modified = "Mon, 07 Sep 2026 20:32:25 GMT"
