title = "Lambda Land"
description = "Lambda: The Ultimate Blog Post—a blog mostly about programming languages, academia, and Emacs"
url = "https://lambdaland.org/atom.xml"
feed_url = "https://lambdaland.org/atom.xml"
author = """

            
              Ashton Wiersdorf
            
          """
slug = "lambda-land"
lastupdated = "2026-09-23T18:24:56.814690325Z"
etag = '"dlf8jmmja3x3m5ux"'
last_modified = "Mon, 14 Sep 2026 18:03:03 GMT"
