datapath = "/home/crocidb/Projects/feeds/library"
tui_auto_update = true
parallel_feed_updates = true

[hooks]
before_tui = "$(bulletty dirs local-config)/sync.sh"
after_tui = "$(bulletty dirs local-config)/sync.sh"
