title = "Loris Cro's Personal Website"
description = "Recent content on Loris Cro's Personal Website"
url = "https://kristoff.it/"
feed_url = "https://kristoff.it/index.xml"
author = "Loris Cro's Personal Website"
slug = "loris-cro-s-personal-website"
lastupdated = "2026-08-07T00:30:01.002998968Z"
etag = 'W/"6a4c7097-2d04"'
last_modified = "Tue, 07 Jul 2026 03:20:55 GMT"
