title = "Loris Cro's Personal Website"
description = "Recent content on Loris Cro's Personal Website"
url = "https://kristoff.it/"
feed_url = "https://kristoff.it/index.xml"
author = "Loris Cro's Personal Website"
slug = "loris-cro-s-personal-website"
lastupdated = "2026-04-30T08:13:00.987911362Z"
