title = "The Luddite"
description = "An Anticapitalist Tech Blog"
url = "https://theluddite.org"
feed_url = "http://theluddite.org/feed.rss"
author = ""
slug = "the-luddite"
lastupdated = "2026-02-11T20:17:01.142374077Z"
