title = "The Luddite"
description = "An Anticapitalist Tech Blog"
url = "https://theluddite.org"
feed_url = "http://theluddite.org/feed.rss"
author = ""
slug = "the-luddite"
lastupdated = "2026-07-23T22:52:41.101917966Z"
