title = "Generalistic writings from @vlnn"
description = "Generalistic writings from @vlnn"
url = "https://vlnn.dev/"
feed_url = "https://vlnn.dev/rss.xml"
author = "Generalistic writings from @vlnn"
slug = "generalistic-writings-from-vlnn"
lastupdated = "2026-09-03T22:47:03.022054280Z"
etag = 'W/"6a954aee-111c4"'
last_modified = "Mon, 31 Aug 2026 09:35:42 GMT"
