title = "Phoronix"
description = "Linux Hardware Reviews, Performance Benchmarks & Open-Source / Free Software News"
url = "https://www.phoronix.com/"
feed_url = "https://www.phoronix.com/rss.php"
author = "Phoronix"
slug = "phoronix"
lastupdated = "2026-09-03T22:47:04.351501664Z"
last_modified = "Thu, 03 Sep 2026 22:42:54 GMT"
