title = "andreinc"
description = "Personal blog of Andrei N. Ciobanu."
url = "/feed.xml"
feed_url = "https://www.andreinc.net/feed.xml"
author = "Andrei Ciobanu"
slug = "andreinc"
lastupdated = "2026-09-08T13:04:56.194310361Z"
etag = '"dfde8c6a7e07f20ad87f21ed1faa0230"'
