title = "andreinc"
description = "Personal blog of Andrei N. Ciobanu."
url = "/feed.xml"
feed_url = "https://www.andreinc.net/feed.xml"
author = "Andrei Ciobanu"
slug = "andreinc"
lastupdated = "2026-08-06T22:26:01.834549790Z"
etag = '"7fb83d3b5c02827b6518f05145535cd1"'
