title = "andreinc"
description = "Personal blog of Andrei N. Ciobanu."
url = "/feed.xml"
feed_url = "https://www.andreinc.net/feed.xml"
author = "Andrei Ciobanu"
slug = "andreinc"
lastupdated = "2026-09-01T19:33:14.023184764Z"
etag = 'W/"6c7bcecde7300b8c1fb6e48a643591b9"'
