title = "PotHix"
description = "Recent content on PotHix"
url = "https://pothix.com/"
feed_url = "http://feeds.feedburner.com/Pothix"
author = ""
slug = "pothix"
lastupdated = "2026-09-27T09:51:02.287289046Z"
last_modified = "Thu, 24 Sep 2026 15:31:51 GMT"
