title = "PotHix"
description = "Recent content on PotHix"
url = "https://pothix.com/"
feed_url = "http://feeds.feedburner.com/Pothix"
author = ""
slug = "pothix"
lastupdated = "2026-10-01T11:34:05.274264092Z"
last_modified = "Thu, 1 Oct 2026 11:10:58 GMT"
