title = "absorptions"
description = "a blog about sound &amp; signals by windytan [oona räisänen]"
url = "https://www.windytan.com/feeds/posts/default"
feed_url = "https://www.windytan.com/feeds/posts/default"
author = "Oona Räisänen"
slug = "absorptions"
lastupdated = "2026-09-08T13:06:50.898340063Z"
etag = 'W/"56812e21c7c1b3dfbc638a5abc747da3b13f72bd6519a535eb2577f006a461f6"'
last_modified = "Mon, 07 Sep 2026 02:54:35 GMT"
