title = "Ratfactor Feed"
description = "Dave Gauer's personal website. Mostly technical articles."
url = "http://ratfactor.com/atom.xml"
feed_url = "http://ratfactor.com/atom.xml"
author = "Dave Gauer"
slug = "ratfactor-feed"
lastupdated = "2025-12-19T13:26:55.945205556Z"
