title = "Ratfactor Feed"
description = "Dave Gauer's personal website. Mostly technical articles."
url = "http://ratfactor.com/atom.xml"
feed_url = "http://ratfactor.com/atom.xml"
author = "Dave Gauer"
slug = "ratfactor-feed"
lastupdated = "2026-02-11T20:17:02.706024930Z"
