title = "Agentultra"
description = "Musings and ramblings on programming and things"
url = "https://agentultra.com"
feed_url = "https://agentultra.com/feed.xml"
author = "Agentultra"
slug = "agentultra"
lastupdated = "2026-08-07T00:30:01.003207992Z"
etag = '"69ef6a6e-124b"'
last_modified = "Mon, 27 Apr 2026 13:53:50 GMT"
