title = "Tom Renner on My place to put things"
description = "Recent content in Tom Renner on My place to put things"
url = "https://tomrenner.com/"
feed_url = "https://tomrenner.com/index.xml"
author = "Tom Renner on My place to put things"
slug = "tom-renner-on-my-place-to-put-things"
lastupdated = "2026-09-08T13:05:01.121757686Z"
etag = 'W/"6a841b97-276fd"'
last_modified = "Tue, 18 Aug 2026 08:45:11 GMT"
