title = "Tom Renner on My place to put things"
description = "Recent content in Tom Renner on My place to put things"
url = "https://tomrenner.com/"
feed_url = "https://tomrenner.com/index.xml"
author = "Tom Renner on My place to put things"
slug = "tom-renner-on-my-place-to-put-things"
lastupdated = "2026-08-06T21:59:29.138493083Z"
etag = 'W/"6a2fd8d0-276a3"'
last_modified = "Mon, 15 Jun 2026 10:49:52 GMT"
