title = "Send More Paramedics"
description = "λ λ λ"
url = "https://blog.fogus.me/feed/"
feed_url = "http://blog.fogus.me/feed/"
author = "Send More Paramedics"
slug = "send-more-paramedics"
lastupdated = "2026-08-06T21:59:28.955793698Z"
etag = '"1e4a-6583918601564"'
last_modified = "Tue, 04 Aug 2026 14:01:45 GMT"
