title = "Pluralistic: Daily links from Cory Doctorow"
description = "No trackers, no ads. Black type, white background. Privacy policy: we don't collect or retain any data at all ever period."
url = "https://pluralistic.net/feed/"
feed_url = "https://pluralistic.net/feed/"
author = "Pluralistic: Daily links from Cory Doctorow"
slug = "pluralistic-daily-links-from-cory-doctorow"
lastupdated = "2025-12-19T13:26:49.440764384Z"
