title = "Programming Posts & Notes on abhinavsarkar.net"
description = "Programming Posts & Notes on abhinavsarkar.net"
url = "https://abhinavsarkar.net/feed.atom"
feed_url = "https://abhinavsarkar.net/feed.atom"
author = "Abhinav Sarkar"
slug = "programming-posts-notes-on-abhinavsarkar-net"
lastupdated = "2026-08-06T21:59:33.558289024Z"
etag = 'W/"6a74fc57-4e4133"'
last_modified = "Thu, 06 Aug 2026 21:27:51 GMT"
