title = "Programming Posts & Notes on abhinavsarkar.net"
description = "Programming Posts & Notes on abhinavsarkar.net"
url = "https://abhinavsarkar.net/feed.atom"
feed_url = "https://abhinavsarkar.net/feed.atom"
author = "Abhinav Sarkar"
slug = "programming-posts-notes-on-abhinavsarkar-net"
lastupdated = "2026-07-21T09:17:41.698776572Z"
