title = "Programming Posts & Notes on abhinavsarkar.net"
description = "Programming Posts & Notes on abhinavsarkar.net"
url = "https://abhinavsarkar.net/feed.atom"
feed_url = "https://abhinavsarkar.net/feed.atom"
author = "Abhinav Sarkar"
slug = "programming-posts-notes-on-abhinavsarkar-net"
lastupdated = "2026-09-08T13:04:58.862098094Z"
etag = 'W/"6a9fff4e-4fd829"'
last_modified = "Tue, 08 Sep 2026 12:27:58 GMT"
