title = "andreinc"
description = "Personal blog of Andrei N. Ciobanu."
url = "/feed.xml"
feed_url = "https://www.andreinc.net/feed.xml"
author = "Andrei Ciobanu"
slug = "andreinc"
lastupdated = "2025-10-31T14:47:20.723307732Z"
