title = "andreinc"
description = "Personal blog of Andrei N. Ciobanu."
url = "/feed.xml"
feed_url = "https://www.andreinc.net/feed.xml"
author = "Andrei Ciobanu"
slug = "andreinc"
lastupdated = "2025-11-07T14:09:26.711620759Z"
