title = "James' Coffee Blog"
description = "James' Coffee Blog"
url = "https://jamesg.blog/longform-feed"
feed_url = "https://jamesg.blog/feeds/posts.xml"
author = "James' Coffee Blog"
slug = "james-coffee-blog"
lastupdated = "2026-02-11T20:17:01.833562789Z"
