title = "AksDev"
description = "Akseli's various rambles and posts about gaming, gamedev, FOSS, programming and other things."
url = "https://akselmo.dev"
feed_url = "https://akselmo.dev/feed.xml"
author = "Akseli"
slug = "aksdev"
lastupdated = "2026-09-03T22:47:04.101871286Z"
etag = '"129e68-65a321fbe8127-gzip"'
last_modified = "Sat, 29 Aug 2026 16:33:07 GMT"
