title = "Languages and Architecture"
description = "A blog on programming languages, software architecture, and Evan Ovadia's other shenanigans!"
url = "https://verdagon.dev/"
feed_url = "https://verdagon.dev/rss.xml"
author = "noreply@verdagon.dev (Evan Ovadia)"
slug = "languages-and-architecture"
lastupdated = "2026-09-03T22:47:40.444461574Z"
etag = '"7695efd08dc7567a1dad08597b1314bdd0e1d5c22c1ac16830aef0f5ef35d82c"'
last_modified = "Sun, 28 Jun 2026 21:21:08 GMT"
