title = "ThingsPool"
description = "ThingsPool"
url = "https://thingspool.net/feed.atom"
feed_url = "https://thingspool.net/feed.atom"
author = "Youngjin Kang"
slug = "thingspool"
lastupdated = "2026-09-08T13:05:00.581109869Z"
etag = 'W/"6aa00482-2351c"'
last_modified = "Tue, 08 Sep 2026 12:50:10 GMT"
