title = "ThingsPool"
description = "ThingsPool"
url = "https://thingspool.net/feed.atom"
feed_url = "https://thingspool.net/feed.atom"
author = "Youngjin Kang"
slug = "thingspool"
lastupdated = "2026-07-21T09:16:58.091361670Z"
