title = "ThingsPool"
description = "ThingsPool"
url = "https://thingspool.net/feed.atom"
feed_url = "https://thingspool.net/feed.atom"
author = "Youngjin Kang"
slug = "thingspool"
lastupdated = "2026-08-07T00:30:02.803769914Z"
etag = 'W/"6a751a4c-22f6f"'
last_modified = "Thu, 06 Aug 2026 23:35:40 GMT"
