title = "𝚟𝚎𝚛𝚖𝚊𝚍𝚎𝚗"
description = "Another ${RANDOM} sysadmin sharing his experiences of work at IT industry."
url = "https://vermaden.wordpress.com/feed/"
feed_url = "https://vermaden.wordpress.com/feed/"
author = "𝚟𝚎𝚛𝚖𝚊𝚍𝚎𝚗"
slug = "vermaden"
lastupdated = "2026-08-07T00:30:00.129107567Z"
last_modified = "Mon, 03 Aug 2026 09:17:01 GMT"
