title = "𝚟𝚎𝚛𝚖𝚊𝚍𝚎𝚗"
description = "Another ${RANDOM} sysadmin sharing his experiences of work at IT industry."
url = "https://vermaden.wordpress.com/feed/"
feed_url = "https://vermaden.wordpress.com/feed/"
author = "𝚟𝚎𝚛𝚖𝚊𝚍𝚎𝚗"
slug = "vermaden"
lastupdated = "2026-09-08T13:04:55.378449526Z"
last_modified = "Mon, 07 Sep 2026 19:42:55 GMT"
