title = "マリウス"
description = "The Journal of マリウス"
url = "https://xn--gckvb8fzb.com/"
feed_url = "https://マリウス.com/index.xml"
author = "marius@xn--gckvb8fzb.com (Marius)"
slug = "mariusu"
lastupdated = "2026-02-11T20:16:58.822173996Z"
