title = "マリウス"
description = "The Journal of マリウス"
url = "https://xn--gckvb8fzb.com/"
feed_url = "https://マリウス.com/index.xml"
author = "marius@xn--gckvb8fzb.com (Marius)"
slug = "mariusu"
lastupdated = "2025-12-17T22:54:10.010606657Z"
