title = "passo.uno"
description = "Recent content on passo.uno"
url = "https://passo.uno/"
feed_url = "https://passo.uno/index.xml"
author = "passo.uno"
slug = "passo-uno"
lastupdated = "2026-08-10T22:25:10.779523641Z"
etag = 'W/"164312b357c3e189e415a298c5325de1"'
