title = "passo.uno"
description = "Recent content on passo.uno"
url = "https://passo.uno/"
feed_url = "https://passo.uno/index.xml"
author = "passo.uno"
slug = "passo-uno"
lastupdated = "2026-09-01T19:33:13.012513240Z"
etag = '"2cb3dc3afc0b82078da1decd9434e9f6"'
