title = "passo.uno"
description = "Recent content on passo.uno"
url = "https://passo.uno/"
feed_url = "https://passo.uno/index.xml"
author = "passo.uno"
slug = "passo-uno"
lastupdated = "2026-08-06T22:26:01.632025305Z"
etag = '"9fe8e2de30120d4e0f4db6a1233344f9"'
