title = "Zig Devlog"
description = "Devlog"
url = "https://ziglang.org/devlog/"
feed_url = "https://ziglang.org/devlog/index.xml"
author = ""
slug = "zig-devlog"
lastupdated = "2025-12-19T13:26:56.613639418Z"
