title = "Zig Devlog"
description = "Devlog"
url = "https://ziglang.org/devlog/"
feed_url = "https://ziglang.org/devlog/index.xml"
author = ""
slug = "zig-devlog"
lastupdated = "2025-10-31T14:47:24.585555436Z"
