title = "gonzalo's log"
description = "log entries"
url = "https://x61.sh/log/"
feed_url = "https://x61.sh/log/rss.xml"
author = "gonzalo's log"
slug = "gonzalo-s-log"
lastupdated = "2026-08-07T00:29:59.921157707Z"
last_modified = "Fri, 27 Mar 2026 08:18:18 GMT"
