title = "gonzalo's log"
description = "log entries"
url = "https://x61.sh/log/"
feed_url = "https://x61.sh/log/rss.xml"
author = "gonzalo's log"
slug = "gonzalo-s-log"
lastupdated = "2026-03-19T16:31:03.845093976Z"
