title = "gonzalo's log"
description = "log entries"
url = "https://x61.sh/log/"
feed_url = "https://x61.sh/log/rss.xml"
author = "gonzalo's log"
slug = "gonzalo-s-log"
lastupdated = "2026-08-06T21:59:22.650912574Z"
last_modified = "Fri, 27 Mar 2026 08:18:18 GMT"
