title = "マリウス"
description = "The Journal of マリウス"
url = "https://xn--gckvb8fzb.com/"
feed_url = "https://マリウス.com/index.xml"
author = "marius@xn--gckvb8fzb.com (Marius)"
slug = "mariusu"
lastupdated = "2026-09-21T09:42:43.153085720Z"
etag = '"6aa83480-2aca4"'
last_modified = "Mon, 14 Sep 2026 17:53:04 GMT"
