title = "GamesIndustry.biz Latest Articles Feed"
description = "This is a feed of the latest articles from GamesIndustry.biz."
url = "https://www.gamesindustry.biz/feed"
feed_url = "https://www.gamesindustry.biz/feed"
author = "GamesIndustry.biz Latest Articles Feed"
slug = "gamesindustry-biz-latest-articles-feed"
lastupdated = "2026-09-21T09:44:40.574796438Z"
last_modified = "Mon, 21 Sep 2026 08:35:21 GMT"
