title = "Daring Fireball"
description = "By John Gruber"
url = "https://daringfireball.net/"
feed_url = "https://daringfireball.net/feeds/main"
author = "John Gruber"
slug = "daring-fireball"
lastupdated = "2026-09-03T22:47:03.131473458Z"
etag = '"49c0564c8e0c680c00d21278c058a703-gzip"'
last_modified = "Thu, 03 Sep 2026 22:46:03 GMT"
