title = "buttonmashing"
description = "Mashing buttons since 1984"
url = "http://buttonmashing.com/feed/"
feed_url = "http://buttonmashing.com/feed/"
author = ""
slug = "buttonmashing"
lastupdated = "2026-02-11T20:16:58.445434041Z"
