title = "absorptions"
description = "a blog about sound &amp; signals by windytan [oona räisänen]"
url = "https://www.windytan.com/feeds/posts/default"
feed_url = "https://www.windytan.com/feeds/posts/default"
author = "Oona Räisänen"
slug = "absorptions"
lastupdated = "2025-10-31T14:47:18.887101897Z"
