title = "Jo's Blog"
description = "Jo's Blog"
url = "https://dead.garden/blog/index.html"
feed_url = "https://dead.garden/blog/feed.xml"
author = "Jo's Blog"
slug = "jo-s-blog"
lastupdated = "2026-09-03T22:47:02.836998960Z"
etag = '"6a95bc2d-2d6b"'
last_modified = "Mon, 31 Aug 2026 17:38:53 GMT"
