title = "Revista O Grito! — Jornalismo cultural que fala de tudo"
description = "Notícias, resenhas e artigos de arte, quadrinhos, cultura pop e cena independente"
url = "https://revistaogrito.com/feed/"
feed_url = "https://revistaogrito.com/feed/"
author = "Revista O Grito! — Jornalismo cultural que fala de tudo"
slug = "revista-o-grito-jornalismo-cultural-que-fala-de-tudo"
lastupdated = "2026-09-03T22:47:03.753552195Z"
etag = '"704b05ba84f526cb9362be0209e9e375"'
last_modified = "Thu, 03 Sep 2026 10:33:00 GMT"
