title = "Scattered Thoughts"
description = "Scattered Thoughts"
url = "https://www.scattered-thoughts.net/atom.xml"
feed_url = "https://www.scattered-thoughts.net/atom.xml"
author = "Jamie Brandon"
slug = "scattered-thoughts"
lastupdated = "2026-08-06T21:59:23.508160886Z"
etag = '"6a610ae4-12963"'
last_modified = "Wed, 22 Jul 2026 18:24:36 GMT"
