title = "Scattered Thoughts"
description = "Scattered Thoughts"
url = "https://www.scattered-thoughts.net/atom.xml"
feed_url = "https://www.scattered-thoughts.net/atom.xml"
author = "Jamie Brandon"
slug = "scattered-thoughts"
lastupdated = "2026-07-22T09:22:13.302515534Z"
