title = "Posts on Nikita Lapkov"
description = "Recent content in Posts on Nikita Lapkov"
url = "https://laplab.me/posts/"
feed_url = "https://laplab.me/posts/index.xml"
author = "Posts on Nikita Lapkov"
slug = "posts-on-nikita-lapkov"
lastupdated = "2025-11-07T14:09:22.921036317Z"
