title = "General Protection Fault"
description = "nicebyte's blog"
url = "https://gpfault.net/rss.xml"
feed_url = "https://gpfault.net/rss.xml"
author = "General Protection Fault"
slug = "general-protection-fault"
lastupdated = "2026-03-20T10:31:27.182864519Z"
