title = "General Protection Fault"
description = "nicebyte's blog"
url = "https://gpfault.net/rss.xml"
feed_url = "https://gpfault.net/rss.xml"
author = "General Protection Fault"
slug = "general-protection-fault"
lastupdated = "2026-08-06T21:59:27.648755320Z"
etag = '"250f92f9b3d85bf0b251b7c5ce659b20"'
last_modified = "Sun, 12 Apr 2026 22:14:52 GMT"
