title = "Agentultra"
description = "Musings and ramblings on programming and things"
url = "https://agentultra.com"
feed_url = "https://agentultra.com/feed.xml"
author = "Agentultra"
slug = "agentultra"
lastupdated = "2025-12-19T13:26:53.127246012Z"
