title = "Agentultra"
description = "Musings and ramblings on programming and things"
url = "https://agentultra.com"
feed_url = "https://agentultra.com/feed.xml"
author = "Agentultra"
slug = "agentultra"
lastupdated = "2025-10-31T14:47:23.342588319Z"
