title = "brennan.day"
description = "Brennan Kenneth Brown is a Queer Métis writer and web developer exploring Indigenous identity, digital culture, and creativity. Personal essays on technology, craft, and human experience from Calgary, Alberta (Treaty 7)."
url = "https://brennan.day"
feed_url = "https://brennan.day/feed.xml"
author = "Brennan Kenneth Brown"
slug = "brennan-day"
lastupdated = "2026-09-08T13:04:55.020306204Z"
etag = '"345c110df1dc5c349e52d8fb0e30505b-ssl-df"'
