title = "Send More Paramedics"
description = "λ λ λ"
url = "https://blog.fogus.me/feed/"
feed_url = "http://blog.fogus.me/feed/"
author = "Send More Paramedics"
slug = "send-more-paramedics"
lastupdated = "2025-12-19T13:26:54.559263368Z"
