title = "Send More Paramedics"
description = "λ λ λ"
url = "https://blog.fogus.me/feed/"
feed_url = "http://blog.fogus.me/feed/"
author = "Send More Paramedics"
slug = "send-more-paramedics"
lastupdated = "2026-02-11T20:17:08.246465532Z"
