title = "Jonas Hietala"
description = "Jonas Hietala"
url = "https://www.jonashietala.se/feed.xml"
feed_url = "https://www.jonashietala.se/feed.xml"
author = "Jonas Hietala"
slug = "jonas-hietala"
lastupdated = "2026-09-30T20:51:46.162874804Z"
etag = '"dlrwvr6m3fnk3fzfp"'
last_modified = "Tue, 29 Sep 2026 15:39:20 GMT"
