title = "Jonas Hietala"
description = "Jonas Hietala"
url = "https://www.jonashietala.se/feed.xml"
feed_url = "https://www.jonashietala.se/feed.xml"
author = "Jonas Hietala"
slug = "jonas-hietala"
lastupdated = "2026-08-24T15:49:19.972107784Z"
etag = '"dkijkk20oao03bqjm"'
last_modified = "Fri, 07 Aug 2026 07:43:30 GMT"
