title = "Jonas Hietala"
description = "Jonas Hietala"
url = "https://www.jonashietala.se/feed.xml"
feed_url = "https://www.jonashietala.se/feed.xml"
author = "Jonas Hietala"
slug = "jonas-hietala"
lastupdated = "2026-08-06T22:26:03.037979364Z"
etag = '"dk5tr0nx0mps38tvj"'
last_modified = "Thu, 23 Jul 2026 08:57:28 GMT"
