title = "ThingsPool"
description = "ThingsPool"
url = "https://thingspool.net/feed.atom"
feed_url = "https://thingspool.net/feed.atom"
author = "Youngjin Kang"
slug = "thingspool"
lastupdated = "2026-09-03T22:47:05.057016835Z"
etag = 'W/"6a975b7b-233f3"'
last_modified = "Tue, 01 Sep 2026 23:10:51 GMT"
