title = "Daniel Lemire's blog"
description = "Daniel Lemire is a software performance expert. He ranks among the top 2% of scientists globally (Stanford/Elsevier 2025) and is one of GitHub's top 1000 most followed developers. "
url = "https://lemire.me/blog/feed/"
feed_url = "https://lemire.me/blog/feed/"
author = "Daniel Lemire's blog"
slug = "daniel-lemire-s-blog"
lastupdated = "2026-08-06T22:26:02.105206844Z"
etag = '"d827fac05d9b11044e4bdc6baedada9c"'
last_modified = "Mon, 03 Aug 2026 20:28:01 GMT"
