title = "Daniel Lemire's blog"
description = "Daniel Lemire is a software performance expert. He ranks among the top 2% of scientists globally (Stanford/Elsevier 2025) and is one of GitHub's top 1000 most followed developers. "
url = "https://lemire.me/blog/feed/"
feed_url = "https://lemire.me/blog/feed/"
author = "Daniel Lemire's blog"
slug = "daniel-lemire-s-blog"
lastupdated = "2026-09-08T13:06:51.210950380Z"
etag = '"87ef3b70d134c61fc8f0a0a11ed149ff"'
last_modified = "Sat, 05 Sep 2026 15:24:37 GMT"
