title = "Daniel Lemire's blog"
description = "Daniel Lemire is a software performance expert. He ranks among the top 2% of scientists globally (Stanford/Elsevier 2025) and is one of GitHub's top 1000 most followed developers. "
url = "https://lemire.me/blog/feed/"
feed_url = "https://lemire.me/blog/feed/"
author = "Daniel Lemire's blog"
slug = "daniel-lemire-s-blog"
lastupdated = "2026-03-19T16:26:22.852934467Z"
