title = "Daring Fireball"
description = "By John Gruber"
url = "https://daringfireball.net/"
feed_url = "https://daringfireball.net/feeds/main"
author = "John Gruber"
slug = "daring-fireball"
lastupdated = "2026-08-10T22:24:07.367815704Z"
etag = '"1b8cf1b17a6d417f5dc20c6f53e2383d-gzip"'
last_modified = "Mon, 10 Aug 2026 22:24:04 GMT"
