title = "Daring Fireball"
description = "By John Gruber"
url = "https://daringfireball.net/"
feed_url = "https://daringfireball.net/feeds/main"
author = "John Gruber"
slug = "daring-fireball"
lastupdated = "2026-09-08T13:04:55.378948887Z"
etag = '"cafe04978733633dc56e036bf7fccc39-gzip"'
last_modified = "Tue, 08 Sep 2026 13:04:04 GMT"
