title = "Matt Keeter"
description = "Matt Keeter"
url = "https://mattkeeter.com/atom.xml"
feed_url = "https://www.mattkeeter.com/atom.xml"
author = "Matt Keeter"
slug = "matt-keeter"
lastupdated = "2026-10-05T08:46:06.226132670Z"
etag = '"8fe1-65c8ebcd47d82-gzip"'
last_modified = "Mon, 28 Sep 2026 17:53:03 GMT"
